# Site
name: "Tech Talks by Ankit Kumar"
title: "Tech Talks by Ankit Kumar"
description: "Ankit Kumar is a Programmer, Technologist, Technical Writer, YouTuber and Tutor"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
google_analytics: ""
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ankit:
    name: Ankit
    display_name: Ankit
    avatar: "assets/images/avatar.png"
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: blogs@ankitkumar.dev
    web: https://www.ankitkumar.dev
    twitter: https://twitter.com/KumarrAnkitt
    description: "Programmer, Technologist, Technical Writer, YouTuber and Tutor"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
